# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rangerCpp <- function(treetype, dependent_variable_name, input_data, variable_names, mtry, num_trees, verbose, seed, num_threads, write_forest, importance_mode_r, min_node_size, split_select_weights, use_split_select_weights, always_split_variable_names, use_always_split_variable_names, status_variable_name, prediction_mode, loaded_forest, snp_data, sample_with_replacement, probability, unordered_variable_names, use_unordered_variable_names, save_memory, splitrule_r, case_weights, use_case_weights, class_weights, predict_all, keep_inbag, sample_fraction, alpha, minprop, holdout, prediction_type_r, num_random_splits, order_snps, oob_error, max_depth, inbag, use_inbag) {
    .Call('_sirus_rangerCpp', PACKAGE = 'sirus', treetype, dependent_variable_name, input_data, variable_names, mtry, num_trees, verbose, seed, num_threads, write_forest, importance_mode_r, min_node_size, split_select_weights, use_split_select_weights, always_split_variable_names, use_always_split_variable_names, status_variable_name, prediction_mode, loaded_forest, snp_data, sample_with_replacement, probability, unordered_variable_names, use_unordered_variable_names, save_memory, splitrule_r, case_weights, use_case_weights, class_weights, predict_all, keep_inbag, sample_fraction, alpha, minprop, holdout, prediction_type_r, num_random_splits, order_snps, oob_error, max_depth, inbag, use_inbag)
}

rangerMergeCpp <- function(numTrees, paths1, proba1, paths2, proba2) {
    .Call('_sirus_rangerMergeCpp', PACKAGE = 'sirus', numTrees, paths1, proba1, paths2, proba2)
}

stabilityMetricCpp <- function(numTrees, proba) {
    .Call('_sirus_stabilityMetricCpp', PACKAGE = 'sirus', numTrees, proba)
}

numSmaller <- function(values, reference) {
    .Call('_sirus_numSmaller', PACKAGE = 'sirus', values, reference)
}

